### ISSUE TITLE
Getting AttributeError: 'DefinedNameDict' object has no attribute 'definedName' error in xl_model = formulas.ExcelModel().loads(file_path).finish() 

### ISSUE THREAD

**Issue by sbdongre** [vinci1it2000/formulas#116] opened 2023-04-11 17:37 UTC
Traceback (most recent call last):
  File "/home/dongre/Documents/Sandeep/Trading_System/Zerodha/learnsql.py", line 291, in <module>
    secure_data = single_secure_data(file_name,name)
  File "/home/dongre/Documents/Sandeep/Trading_System/Zerodha/learnsql.py", line 205, in single_secure_data
    xl_model = formulas.ExcelModel().loads(file_path).finish() #formulas.ExcelModel().loads(file_path).finish()
  File "/home/dongre/Documents/Sandeep/Trading_System/Zerodha/venv/lib/python3.10/site-packages/formulas/excel/__init__.py", line 108, in loads
    self.load(filename)
  File "/home/dongre/Documents/Sandeep/Trading_System/Zerodha/venv/lib/python3.10/site-packages/formulas/excel/__init__.py", line 112, in load
    book, context = self.add_book(filename)
  File "/home/dongre/Documents/Sandeep/Trading_System/Zerodha/venv/lib/python3.10/site-packages/formulas/excel/__init__.py", line 188, in add_book
    data['references'] = self.add_references(book, context=context)
  File "/home/dongre/Documents/Sandeep/Trading_System/Zerodha/venv/lib/python3.10/site-packages/formulas/excel/__init__.py", line 93, in add_references
    for n in book.defined_names.definedName:
AttributeError: 'DefinedNameDict' object has no attribute 'definedName'

**Comment by AlirezaRa94** [comment] 2023-04-21 03:28
I have the same issue as well.

**Comment by MizsakPeterEcon** [comment] 2023-04-24 12:49
This is duplicate of issue #114 (which is already handled in the 'dev' branch, just not released yet).

**Comment by vinci1it2000** [comment] 2023-11-13 10:36
duplicate of issue https://github.com/vinci1it2000/formulas/issues/114

**Closed by vinci1it2000** 2023-11-13 10:36 UTC
Labels: duplicate
