### ISSUE TITLE
Range Assembly construction infinite loop

### ISSUE THREAD

**Issue by owinebar** [vinci1it2000/formulas#97] opened 2022-05-07 12:18 UTC
**Describe the bug**
Range Assembly construction appears to go into an infinite loop and consume unbounded memory with some very complicated sheets with complicated array formulas and lookup functions

**To Reproduce**
I do not have one I can share.  I suspect it's happening in the code that attempts to partition the range assembly construction, but I haven't nailed it down.  

1. '...'
2. '....'
3. '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by vinci1it2000** [comment] 2022-06-28 16:26
Duplicate of #98

**Closed by vinci1it2000** 2022-06-28 16:26 UTC
Labels: duplicate
